/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq.tables.records;


import com.imzcc.plugins.module.jooq.tables.AfdianOrder;
import com.imzcc.plugins.module.jooq.tables.interfaces.IAfdianOrder;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AfdianOrderRecord extends UpdatableRecordImpl<AfdianOrderRecord> implements Record16<String, String, String, String, String, Long, String, String, Long, String, String, Long, String, String, String, String>, IAfdianOrder {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Afdian_Order.out_trade_no</code>.
     */
    @Override
    public void setOutTradeNo(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>Afdian_Order.out_trade_no</code>.
     */
    @Override
    public String getOutTradeNo() {
        return (String) get(0);
    }

    /**
     * Setter for <code>Afdian_Order.custom_order_id</code>.
     */
    @Override
    public void setCustomOrderId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Afdian_Order.custom_order_id</code>.
     */
    @Override
    public String getCustomOrderId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Afdian_Order.user_id</code>.
     */
    @Override
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Afdian_Order.user_id</code>.
     */
    @Override
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Afdian_Order.user_private_id</code>.
     */
    @Override
    public void setUserPrivateId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Afdian_Order.user_private_id</code>.
     */
    @Override
    public String getUserPrivateId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Afdian_Order.plan_id</code>.
     */
    @Override
    public void setPlanId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Afdian_Order.plan_id</code>.
     */
    @Override
    public String getPlanId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>Afdian_Order.month</code>.
     */
    @Override
    public void setMonth(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>Afdian_Order.month</code>.
     */
    @Override
    public Long getMonth() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>Afdian_Order.total_amount</code>.
     */
    @Override
    public void setTotalAmount(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>Afdian_Order.total_amount</code>.
     */
    @Override
    public String getTotalAmount() {
        return (String) get(6);
    }

    /**
     * Setter for <code>Afdian_Order.show_amount</code>.
     */
    @Override
    public void setShowAmount(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>Afdian_Order.show_amount</code>.
     */
    @Override
    public String getShowAmount() {
        return (String) get(7);
    }

    /**
     * Setter for <code>Afdian_Order.status</code>.
     */
    @Override
    public void setStatus(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>Afdian_Order.status</code>.
     */
    @Override
    public Long getStatus() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>Afdian_Order.remark</code>.
     */
    @Override
    public void setRemark(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>Afdian_Order.remark</code>.
     */
    @Override
    public String getRemark() {
        return (String) get(9);
    }

    /**
     * Setter for <code>Afdian_Order.redeem_id</code>.
     */
    @Override
    public void setRedeemId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>Afdian_Order.redeem_id</code>.
     */
    @Override
    public String getRedeemId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>Afdian_Order.product_type</code>.
     */
    @Override
    public void setProductType(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>Afdian_Order.product_type</code>.
     */
    @Override
    public Long getProductType() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>Afdian_Order.discount</code>.
     */
    @Override
    public void setDiscount(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>Afdian_Order.discount</code>.
     */
    @Override
    public String getDiscount() {
        return (String) get(12);
    }

    /**
     * Setter for <code>Afdian_Order.address_person</code>.
     */
    @Override
    public void setAddressPerson(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>Afdian_Order.address_person</code>.
     */
    @Override
    public String getAddressPerson() {
        return (String) get(13);
    }

    /**
     * Setter for <code>Afdian_Order.address_phone</code>.
     */
    @Override
    public void setAddressPhone(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>Afdian_Order.address_phone</code>.
     */
    @Override
    public String getAddressPhone() {
        return (String) get(14);
    }

    /**
     * Setter for <code>Afdian_Order.address_address</code>.
     */
    @Override
    public void setAddressAddress(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>Afdian_Order.address_address</code>.
     */
    @Override
    public String getAddressAddress() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<String, String, String, String, String, Long, String, String, Long, String, String, Long, String, String, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<String, String, String, String, String, Long, String, String, Long, String, String, Long, String, String, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AfdianOrder.AFDIAN_ORDER.OUT_TRADE_NO;
    }

    @Override
    public Field<String> field2() {
        return AfdianOrder.AFDIAN_ORDER.CUSTOM_ORDER_ID;
    }

    @Override
    public Field<String> field3() {
        return AfdianOrder.AFDIAN_ORDER.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return AfdianOrder.AFDIAN_ORDER.USER_PRIVATE_ID;
    }

    @Override
    public Field<String> field5() {
        return AfdianOrder.AFDIAN_ORDER.PLAN_ID;
    }

    @Override
    public Field<Long> field6() {
        return AfdianOrder.AFDIAN_ORDER.MONTH;
    }

    @Override
    public Field<String> field7() {
        return AfdianOrder.AFDIAN_ORDER.TOTAL_AMOUNT;
    }

    @Override
    public Field<String> field8() {
        return AfdianOrder.AFDIAN_ORDER.SHOW_AMOUNT;
    }

    @Override
    public Field<Long> field9() {
        return AfdianOrder.AFDIAN_ORDER.STATUS;
    }

    @Override
    public Field<String> field10() {
        return AfdianOrder.AFDIAN_ORDER.REMARK;
    }

    @Override
    public Field<String> field11() {
        return AfdianOrder.AFDIAN_ORDER.REDEEM_ID;
    }

    @Override
    public Field<Long> field12() {
        return AfdianOrder.AFDIAN_ORDER.PRODUCT_TYPE;
    }

    @Override
    public Field<String> field13() {
        return AfdianOrder.AFDIAN_ORDER.DISCOUNT;
    }

    @Override
    public Field<String> field14() {
        return AfdianOrder.AFDIAN_ORDER.ADDRESS_PERSON;
    }

    @Override
    public Field<String> field15() {
        return AfdianOrder.AFDIAN_ORDER.ADDRESS_PHONE;
    }

    @Override
    public Field<String> field16() {
        return AfdianOrder.AFDIAN_ORDER.ADDRESS_ADDRESS;
    }

    @Override
    public String component1() {
        return getOutTradeNo();
    }

    @Override
    public String component2() {
        return getCustomOrderId();
    }

    @Override
    public String component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getUserPrivateId();
    }

    @Override
    public String component5() {
        return getPlanId();
    }

    @Override
    public Long component6() {
        return getMonth();
    }

    @Override
    public String component7() {
        return getTotalAmount();
    }

    @Override
    public String component8() {
        return getShowAmount();
    }

    @Override
    public Long component9() {
        return getStatus();
    }

    @Override
    public String component10() {
        return getRemark();
    }

    @Override
    public String component11() {
        return getRedeemId();
    }

    @Override
    public Long component12() {
        return getProductType();
    }

    @Override
    public String component13() {
        return getDiscount();
    }

    @Override
    public String component14() {
        return getAddressPerson();
    }

    @Override
    public String component15() {
        return getAddressPhone();
    }

    @Override
    public String component16() {
        return getAddressAddress();
    }

    @Override
    public String value1() {
        return getOutTradeNo();
    }

    @Override
    public String value2() {
        return getCustomOrderId();
    }

    @Override
    public String value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getUserPrivateId();
    }

    @Override
    public String value5() {
        return getPlanId();
    }

    @Override
    public Long value6() {
        return getMonth();
    }

    @Override
    public String value7() {
        return getTotalAmount();
    }

    @Override
    public String value8() {
        return getShowAmount();
    }

    @Override
    public Long value9() {
        return getStatus();
    }

    @Override
    public String value10() {
        return getRemark();
    }

    @Override
    public String value11() {
        return getRedeemId();
    }

    @Override
    public Long value12() {
        return getProductType();
    }

    @Override
    public String value13() {
        return getDiscount();
    }

    @Override
    public String value14() {
        return getAddressPerson();
    }

    @Override
    public String value15() {
        return getAddressPhone();
    }

    @Override
    public String value16() {
        return getAddressAddress();
    }

    @Override
    public AfdianOrderRecord value1(String value) {
        setOutTradeNo(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value2(String value) {
        setCustomOrderId(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value3(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value4(String value) {
        setUserPrivateId(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value5(String value) {
        setPlanId(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value6(Long value) {
        setMonth(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value7(String value) {
        setTotalAmount(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value8(String value) {
        setShowAmount(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value9(Long value) {
        setStatus(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value10(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value11(String value) {
        setRedeemId(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value12(Long value) {
        setProductType(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value13(String value) {
        setDiscount(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value14(String value) {
        setAddressPerson(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value15(String value) {
        setAddressPhone(value);
        return this;
    }

    @Override
    public AfdianOrderRecord value16(String value) {
        setAddressAddress(value);
        return this;
    }

    @Override
    public AfdianOrderRecord values(String value1, String value2, String value3, String value4, String value5, Long value6, String value7, String value8, Long value9, String value10, String value11, Long value12, String value13, String value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAfdianOrder from) {
        setOutTradeNo(from.getOutTradeNo());
        setCustomOrderId(from.getCustomOrderId());
        setUserId(from.getUserId());
        setUserPrivateId(from.getUserPrivateId());
        setPlanId(from.getPlanId());
        setMonth(from.getMonth());
        setTotalAmount(from.getTotalAmount());
        setShowAmount(from.getShowAmount());
        setStatus(from.getStatus());
        setRemark(from.getRemark());
        setRedeemId(from.getRedeemId());
        setProductType(from.getProductType());
        setDiscount(from.getDiscount());
        setAddressPerson(from.getAddressPerson());
        setAddressPhone(from.getAddressPhone());
        setAddressAddress(from.getAddressAddress());
    }

    @Override
    public <E extends IAfdianOrder> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AfdianOrderRecord
     */
    public AfdianOrderRecord() {
        super(AfdianOrder.AFDIAN_ORDER);
    }

    /**
     * Create a detached, initialised AfdianOrderRecord
     */
    public AfdianOrderRecord(String outTradeNo, String customOrderId, String userId, String userPrivateId, String planId, Long month, String totalAmount, String showAmount, Long status, String remark, String redeemId, Long productType, String discount, String addressPerson, String addressPhone, String addressAddress) {
        super(AfdianOrder.AFDIAN_ORDER);

        setOutTradeNo(outTradeNo);
        setCustomOrderId(customOrderId);
        setUserId(userId);
        setUserPrivateId(userPrivateId);
        setPlanId(planId);
        setMonth(month);
        setTotalAmount(totalAmount);
        setShowAmount(showAmount);
        setStatus(status);
        setRemark(remark);
        setRedeemId(redeemId);
        setProductType(productType);
        setDiscount(discount);
        setAddressPerson(addressPerson);
        setAddressPhone(addressPhone);
        setAddressAddress(addressAddress);
    }

    /**
     * Create a detached, initialised AfdianOrderRecord
     */
    public AfdianOrderRecord(com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder value) {
        super(AfdianOrder.AFDIAN_ORDER);

        if (value != null) {
            setOutTradeNo(value.getOutTradeNo());
            setCustomOrderId(value.getCustomOrderId());
            setUserId(value.getUserId());
            setUserPrivateId(value.getUserPrivateId());
            setPlanId(value.getPlanId());
            setMonth(value.getMonth());
            setTotalAmount(value.getTotalAmount());
            setShowAmount(value.getShowAmount());
            setStatus(value.getStatus());
            setRemark(value.getRemark());
            setRedeemId(value.getRedeemId());
            setProductType(value.getProductType());
            setDiscount(value.getDiscount());
            setAddressPerson(value.getAddressPerson());
            setAddressPhone(value.getAddressPhone());
            setAddressAddress(value.getAddressAddress());
        }
    }
}
