/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq.tables.records;


import com.imzcc.plugins.module.jooq.tables.AfdianPatched;
import com.imzcc.plugins.module.jooq.tables.interfaces.IAfdianPatched;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AfdianPatchedRecord extends UpdatableRecordImpl<AfdianPatchedRecord> implements Record2<String, String>, IAfdianPatched {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Afdian_Patched.uuid</code>.
     */
    @Override
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>Afdian_Patched.uuid</code>.
     */
    @Override
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>Afdian_Patched.out_trade_no</code>.
     */
    @Override
    public void setOutTradeNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Afdian_Patched.out_trade_no</code>.
     */
    @Override
    public String getOutTradeNo() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AfdianPatched.AFDIAN_PATCHED.UUID;
    }

    @Override
    public Field<String> field2() {
        return AfdianPatched.AFDIAN_PATCHED.OUT_TRADE_NO;
    }

    @Override
    public String component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getOutTradeNo();
    }

    @Override
    public String value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getOutTradeNo();
    }

    @Override
    public AfdianPatchedRecord value1(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public AfdianPatchedRecord value2(String value) {
        setOutTradeNo(value);
        return this;
    }

    @Override
    public AfdianPatchedRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAfdianPatched from) {
        setUuid(from.getUuid());
        setOutTradeNo(from.getOutTradeNo());
    }

    @Override
    public <E extends IAfdianPatched> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AfdianPatchedRecord
     */
    public AfdianPatchedRecord() {
        super(AfdianPatched.AFDIAN_PATCHED);
    }

    /**
     * Create a detached, initialised AfdianPatchedRecord
     */
    public AfdianPatchedRecord(String uuid, String outTradeNo) {
        super(AfdianPatched.AFDIAN_PATCHED);

        setUuid(uuid);
        setOutTradeNo(outTradeNo);
    }

    /**
     * Create a detached, initialised AfdianPatchedRecord
     */
    public AfdianPatchedRecord(com.imzcc.plugins.module.jooq.tables.pojos.AfdianPatched value) {
        super(AfdianPatched.AFDIAN_PATCHED);

        if (value != null) {
            setUuid(value.getUuid());
            setOutTradeNo(value.getOutTradeNo());
        }
    }
}
