/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq.tables;


import com.imzcc.plugins.module.jooq.DefaultSchema;
import com.imzcc.plugins.module.jooq.Keys;
import com.imzcc.plugins.module.jooq.tables.records.AfdianPatchedRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AfdianPatched extends TableImpl<AfdianPatchedRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Afdian_Patched</code>
     */
    public static final AfdianPatched AFDIAN_PATCHED = new AfdianPatched();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AfdianPatchedRecord> getRecordType() {
        return AfdianPatchedRecord.class;
    }

    /**
     * The column <code>Afdian_Patched.uuid</code>.
     */
    public final TableField<AfdianPatchedRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Afdian_Patched.out_trade_no</code>.
     */
    public final TableField<AfdianPatchedRecord, String> OUT_TRADE_NO = createField(DSL.name("out_trade_no"), SQLDataType.CLOB.nullable(false), this, "");

    private AfdianPatched(Name alias, Table<AfdianPatchedRecord> aliased) {
        this(alias, aliased, null);
    }

    private AfdianPatched(Name alias, Table<AfdianPatchedRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Afdian_Patched</code> table reference
     */
    public AfdianPatched(String alias) {
        this(DSL.name(alias), AFDIAN_PATCHED);
    }

    /**
     * Create an aliased <code>Afdian_Patched</code> table reference
     */
    public AfdianPatched(Name alias) {
        this(alias, AFDIAN_PATCHED);
    }

    /**
     * Create a <code>Afdian_Patched</code> table reference
     */
    public AfdianPatched() {
        this(DSL.name("Afdian_Patched"), null);
    }

    public <O extends Record> AfdianPatched(Table<O> child, ForeignKey<O, AfdianPatchedRecord> key) {
        super(child, key, AFDIAN_PATCHED);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<AfdianPatchedRecord> getPrimaryKey() {
        return Keys.AFDIAN_PATCHED__PK_AFDIAN_PATCHED;
    }

    @Override
    public AfdianPatched as(String alias) {
        return new AfdianPatched(DSL.name(alias), this);
    }

    @Override
    public AfdianPatched as(Name alias) {
        return new AfdianPatched(alias, this);
    }

    @Override
    public AfdianPatched as(Table<?> alias) {
        return new AfdianPatched(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AfdianPatched rename(String name) {
        return new AfdianPatched(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AfdianPatched rename(Name name) {
        return new AfdianPatched(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AfdianPatched rename(Table<?> name) {
        return new AfdianPatched(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
