/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq;


import com.imzcc.plugins.module.jooq.tables.AfdianOrder;
import com.imzcc.plugins.module.jooq.tables.AfdianPatched;
import com.imzcc.plugins.module.jooq.tables.AfdianPlayer;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>Afdian_Order</code>.
     */
    public final AfdianOrder AFDIAN_ORDER = AfdianOrder.AFDIAN_ORDER;

    /**
     * The table <code>Afdian_Patched</code>.
     */
    public final AfdianPatched AFDIAN_PATCHED = AfdianPatched.AFDIAN_PATCHED;

    /**
     * The table <code>Afdian_Player</code>.
     */
    public final AfdianPlayer AFDIAN_PLAYER = AfdianPlayer.AFDIAN_PLAYER;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AfdianOrder.AFDIAN_ORDER,
            AfdianPatched.AFDIAN_PATCHED,
            AfdianPlayer.AFDIAN_PLAYER
        );
    }
}
