/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq;


import com.imzcc.plugins.module.jooq.tables.AfdianOrder;
import com.imzcc.plugins.module.jooq.tables.AfdianPatched;
import com.imzcc.plugins.module.jooq.tables.AfdianPlayer;
import com.imzcc.plugins.module.jooq.tables.records.AfdianOrderRecord;
import com.imzcc.plugins.module.jooq.tables.records.AfdianPatchedRecord;
import com.imzcc.plugins.module.jooq.tables.records.AfdianPlayerRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AfdianOrderRecord> AFDIAN_ORDER__PK_AFDIAN_ORDER = Internal.createUniqueKey(AfdianOrder.AFDIAN_ORDER, DSL.name("pk_Afdian_Order"), new TableField[] { AfdianOrder.AFDIAN_ORDER.OUT_TRADE_NO }, true);
    public static final UniqueKey<AfdianPatchedRecord> AFDIAN_PATCHED__PK_AFDIAN_PATCHED = Internal.createUniqueKey(AfdianPatched.AFDIAN_PATCHED, DSL.name("pk_Afdian_Patched"), new TableField[] { AfdianPatched.AFDIAN_PATCHED.UUID, AfdianPatched.AFDIAN_PATCHED.OUT_TRADE_NO }, true);
    public static final UniqueKey<AfdianPlayerRecord> AFDIAN_PLAYER__PK_AFDIAN_PLAYER = Internal.createUniqueKey(AfdianPlayer.AFDIAN_PLAYER, DSL.name("pk_Afdian_Player"), new TableField[] { AfdianPlayer.AFDIAN_PLAYER.UUID }, true);
}
