/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq;


import com.imzcc.plugins.module.jooq.tables.AfdianOrder;
import com.imzcc.plugins.module.jooq.tables.AfdianPatched;
import com.imzcc.plugins.module.jooq.tables.AfdianPlayer;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Afdian_Order</code>.
     */
    public static final AfdianOrder AFDIAN_ORDER = AfdianOrder.AFDIAN_ORDER;

    /**
     * The table <code>Afdian_Patched</code>.
     */
    public static final AfdianPatched AFDIAN_PATCHED = AfdianPatched.AFDIAN_PATCHED;

    /**
     * The table <code>Afdian_Player</code>.
     */
    public static final AfdianPlayer AFDIAN_PLAYER = AfdianPlayer.AFDIAN_PLAYER;
}
