/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq.tables.pojos;


import com.imzcc.plugins.module.jooq.tables.interfaces.IAfdianPlayer;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AfdianPlayer implements IAfdianPlayer {

    private static final long serialVersionUID = 1L;

    private String uuid;
    private String playerName;
    private String userId;

    public AfdianPlayer() {}

    public AfdianPlayer(IAfdianPlayer value) {
        this.uuid = value.getUuid();
        this.playerName = value.getPlayerName();
        this.userId = value.getUserId();
    }

    public AfdianPlayer(
        String uuid,
        String playerName,
        String userId
    ) {
        this.uuid = uuid;
        this.playerName = playerName;
        this.userId = userId;
    }

    /**
     * Getter for <code>Afdian_Player.uuid</code>.
     */
    @Override
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>Afdian_Player.uuid</code>.
     */
    @Override
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * Getter for <code>Afdian_Player.player_name</code>.
     */
    @Override
    public String getPlayerName() {
        return this.playerName;
    }

    /**
     * Setter for <code>Afdian_Player.player_name</code>.
     */
    @Override
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    /**
     * Getter for <code>Afdian_Player.user_id</code>.
     */
    @Override
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>Afdian_Player.user_id</code>.
     */
    @Override
    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AfdianPlayer other = (AfdianPlayer) obj;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!this.uuid.equals(other.uuid))
            return false;
        if (this.playerName == null) {
            if (other.playerName != null)
                return false;
        }
        else if (!this.playerName.equals(other.playerName))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.playerName == null) ? 0 : this.playerName.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AfdianPlayer (");

        sb.append(uuid);
        sb.append(", ").append(playerName);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAfdianPlayer from) {
        setUuid(from.getUuid());
        setPlayerName(from.getPlayerName());
        setUserId(from.getUserId());
    }

    @Override
    public <E extends IAfdianPlayer> E into(E into) {
        into.from(this);
        return into;
    }
}
