/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq.tables.pojos;


import com.imzcc.plugins.module.jooq.tables.interfaces.IAfdianPatched;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AfdianPatched implements IAfdianPatched {

    private static final long serialVersionUID = 1L;

    private String uuid;
    private String outTradeNo;

    public AfdianPatched() {}

    public AfdianPatched(IAfdianPatched value) {
        this.uuid = value.getUuid();
        this.outTradeNo = value.getOutTradeNo();
    }

    public AfdianPatched(
        String uuid,
        String outTradeNo
    ) {
        this.uuid = uuid;
        this.outTradeNo = outTradeNo;
    }

    /**
     * Getter for <code>Afdian_Patched.uuid</code>.
     */
    @Override
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>Afdian_Patched.uuid</code>.
     */
    @Override
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * Getter for <code>Afdian_Patched.out_trade_no</code>.
     */
    @Override
    public String getOutTradeNo() {
        return this.outTradeNo;
    }

    /**
     * Setter for <code>Afdian_Patched.out_trade_no</code>.
     */
    @Override
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AfdianPatched other = (AfdianPatched) obj;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!this.uuid.equals(other.uuid))
            return false;
        if (this.outTradeNo == null) {
            if (other.outTradeNo != null)
                return false;
        }
        else if (!this.outTradeNo.equals(other.outTradeNo))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.outTradeNo == null) ? 0 : this.outTradeNo.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AfdianPatched (");

        sb.append(uuid);
        sb.append(", ").append(outTradeNo);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAfdianPatched from) {
        setUuid(from.getUuid());
        setOutTradeNo(from.getOutTradeNo());
    }

    @Override
    public <E extends IAfdianPatched> E into(E into) {
        into.from(this);
        return into;
    }
}
