/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq.tables.daos;


import com.imzcc.plugins.module.jooq.tables.AfdianPlayer;
import com.imzcc.plugins.module.jooq.tables.records.AfdianPlayerRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AfdianPlayerDao extends DAOImpl<AfdianPlayerRecord, com.imzcc.plugins.module.jooq.tables.pojos.AfdianPlayer, String> {

    /**
     * Create a new AfdianPlayerDao without any configuration
     */
    public AfdianPlayerDao() {
        super(AfdianPlayer.AFDIAN_PLAYER, com.imzcc.plugins.module.jooq.tables.pojos.AfdianPlayer.class);
    }

    /**
     * Create a new AfdianPlayerDao with an attached configuration
     */
    public AfdianPlayerDao(Configuration configuration) {
        super(AfdianPlayer.AFDIAN_PLAYER, com.imzcc.plugins.module.jooq.tables.pojos.AfdianPlayer.class, configuration);
    }

    @Override
    public String getId(com.imzcc.plugins.module.jooq.tables.pojos.AfdianPlayer object) {
        return object.getUuid();
    }

    /**
     * Fetch records that have <code>uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianPlayer> fetchRangeOfUuid(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianPlayer.AFDIAN_PLAYER.UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uuid IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianPlayer> fetchByUuid(String... values) {
        return fetch(AfdianPlayer.AFDIAN_PLAYER.UUID, values);
    }

    /**
     * Fetch a unique record that has <code>uuid = value</code>
     */
    public com.imzcc.plugins.module.jooq.tables.pojos.AfdianPlayer fetchOneByUuid(String value) {
        return fetchOne(AfdianPlayer.AFDIAN_PLAYER.UUID, value);
    }

    /**
     * Fetch a unique record that has <code>uuid = value</code>
     */
    public Optional<com.imzcc.plugins.module.jooq.tables.pojos.AfdianPlayer> fetchOptionalByUuid(String value) {
        return fetchOptional(AfdianPlayer.AFDIAN_PLAYER.UUID, value);
    }

    /**
     * Fetch records that have <code>player_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianPlayer> fetchRangeOfPlayerName(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianPlayer.AFDIAN_PLAYER.PLAYER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>player_name IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianPlayer> fetchByPlayerName(String... values) {
        return fetch(AfdianPlayer.AFDIAN_PLAYER.PLAYER_NAME, values);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianPlayer> fetchRangeOfUserId(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianPlayer.AFDIAN_PLAYER.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianPlayer> fetchByUserId(String... values) {
        return fetch(AfdianPlayer.AFDIAN_PLAYER.USER_ID, values);
    }
}
