/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq.tables.daos;


import com.imzcc.plugins.module.jooq.tables.AfdianOrder;
import com.imzcc.plugins.module.jooq.tables.records.AfdianOrderRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AfdianOrderDao extends DAOImpl<AfdianOrderRecord, com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder, String> {

    /**
     * Create a new AfdianOrderDao without any configuration
     */
    public AfdianOrderDao() {
        super(AfdianOrder.AFDIAN_ORDER, com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder.class);
    }

    /**
     * Create a new AfdianOrderDao with an attached configuration
     */
    public AfdianOrderDao(Configuration configuration) {
        super(AfdianOrder.AFDIAN_ORDER, com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder.class, configuration);
    }

    @Override
    public String getId(com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder object) {
        return object.getOutTradeNo();
    }

    /**
     * Fetch records that have <code>out_trade_no BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfOutTradeNo(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.OUT_TRADE_NO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>out_trade_no IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByOutTradeNo(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.OUT_TRADE_NO, values);
    }

    /**
     * Fetch a unique record that has <code>out_trade_no = value</code>
     */
    public com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder fetchOneByOutTradeNo(String value) {
        return fetchOne(AfdianOrder.AFDIAN_ORDER.OUT_TRADE_NO, value);
    }

    /**
     * Fetch a unique record that has <code>out_trade_no = value</code>
     */
    public Optional<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchOptionalByOutTradeNo(String value) {
        return fetchOptional(AfdianOrder.AFDIAN_ORDER.OUT_TRADE_NO, value);
    }

    /**
     * Fetch records that have <code>custom_order_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfCustomOrderId(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.CUSTOM_ORDER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>custom_order_id IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByCustomOrderId(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.CUSTOM_ORDER_ID, values);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfUserId(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByUserId(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.USER_ID, values);
    }

    /**
     * Fetch records that have <code>user_private_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfUserPrivateId(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.USER_PRIVATE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_private_id IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByUserPrivateId(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.USER_PRIVATE_ID, values);
    }

    /**
     * Fetch records that have <code>plan_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfPlanId(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.PLAN_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>plan_id IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByPlanId(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.PLAN_ID, values);
    }

    /**
     * Fetch records that have <code>month BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfMonth(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.MONTH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>month IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByMonth(Long... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.MONTH, values);
    }

    /**
     * Fetch records that have <code>total_amount BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfTotalAmount(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.TOTAL_AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>total_amount IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByTotalAmount(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.TOTAL_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>show_amount BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfShowAmount(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.SHOW_AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>show_amount IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByShowAmount(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.SHOW_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfStatus(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByStatus(Long... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.STATUS, values);
    }

    /**
     * Fetch records that have <code>remark BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfRemark(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.REMARK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByRemark(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.REMARK, values);
    }

    /**
     * Fetch records that have <code>redeem_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfRedeemId(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.REDEEM_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>redeem_id IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByRedeemId(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.REDEEM_ID, values);
    }

    /**
     * Fetch records that have <code>product_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfProductType(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.PRODUCT_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_type IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByProductType(Long... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.PRODUCT_TYPE, values);
    }

    /**
     * Fetch records that have <code>discount BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfDiscount(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.DISCOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>discount IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByDiscount(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.DISCOUNT, values);
    }

    /**
     * Fetch records that have <code>address_person BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfAddressPerson(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.ADDRESS_PERSON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>address_person IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByAddressPerson(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.ADDRESS_PERSON, values);
    }

    /**
     * Fetch records that have <code>address_phone BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfAddressPhone(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.ADDRESS_PHONE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>address_phone IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByAddressPhone(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.ADDRESS_PHONE, values);
    }

    /**
     * Fetch records that have <code>address_address BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchRangeOfAddressAddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianOrder.AFDIAN_ORDER.ADDRESS_ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>address_address IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianOrder> fetchByAddressAddress(String... values) {
        return fetch(AfdianOrder.AFDIAN_ORDER.ADDRESS_ADDRESS, values);
    }
}
