/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq.tables.daos;


import com.imzcc.plugins.module.jooq.tables.AfdianPatched;
import com.imzcc.plugins.module.jooq.tables.records.AfdianPatchedRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AfdianPatchedDao extends DAOImpl<AfdianPatchedRecord, com.imzcc.plugins.module.jooq.tables.pojos.AfdianPatched, Record2<String, String>> {

    /**
     * Create a new AfdianPatchedDao without any configuration
     */
    public AfdianPatchedDao() {
        super(AfdianPatched.AFDIAN_PATCHED, com.imzcc.plugins.module.jooq.tables.pojos.AfdianPatched.class);
    }

    /**
     * Create a new AfdianPatchedDao with an attached configuration
     */
    public AfdianPatchedDao(Configuration configuration) {
        super(AfdianPatched.AFDIAN_PATCHED, com.imzcc.plugins.module.jooq.tables.pojos.AfdianPatched.class, configuration);
    }

    @Override
    public Record2<String, String> getId(com.imzcc.plugins.module.jooq.tables.pojos.AfdianPatched object) {
        return compositeKeyRecord(object.getUuid(), object.getOutTradeNo());
    }

    /**
     * Fetch records that have <code>uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianPatched> fetchRangeOfUuid(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianPatched.AFDIAN_PATCHED.UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uuid IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianPatched> fetchByUuid(String... values) {
        return fetch(AfdianPatched.AFDIAN_PATCHED.UUID, values);
    }

    /**
     * Fetch records that have <code>out_trade_no BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianPatched> fetchRangeOfOutTradeNo(String lowerInclusive, String upperInclusive) {
        return fetchRange(AfdianPatched.AFDIAN_PATCHED.OUT_TRADE_NO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>out_trade_no IN (values)</code>
     */
    public List<com.imzcc.plugins.module.jooq.tables.pojos.AfdianPatched> fetchByOutTradeNo(String... values) {
        return fetch(AfdianPatched.AFDIAN_PATCHED.OUT_TRADE_NO, values);
    }
}
