/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAfdianPatched extends Serializable {

    /**
     * Setter for <code>Afdian_Patched.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>Afdian_Patched.uuid</code>.
     */
    public String getUuid();

    /**
     * Setter for <code>Afdian_Patched.out_trade_no</code>.
     */
    public void setOutTradeNo(String value);

    /**
     * Getter for <code>Afdian_Patched.out_trade_no</code>.
     */
    public String getOutTradeNo();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IAfdianPatched
     */
    public void from(IAfdianPatched from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IAfdianPatched
     */
    public <E extends IAfdianPatched> E into(E into);
}
