/*
 * This file is generated by jOOQ.
 */
package com.imzcc.plugins.module.jooq.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAfdianPlayer extends Serializable {

    /**
     * Setter for <code>Afdian_Player.uuid</code>.
     */
    public void setUuid(String value);

    /**
     * Getter for <code>Afdian_Player.uuid</code>.
     */
    public String getUuid();

    /**
     * Setter for <code>Afdian_Player.player_name</code>.
     */
    public void setPlayerName(String value);

    /**
     * Getter for <code>Afdian_Player.player_name</code>.
     */
    public String getPlayerName();

    /**
     * Setter for <code>Afdian_Player.user_id</code>.
     */
    public void setUserId(String value);

    /**
     * Getter for <code>Afdian_Player.user_id</code>.
     */
    public String getUserId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IAfdianPlayer
     */
    public void from(IAfdianPlayer from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IAfdianPlayer
     */
    public <E extends IAfdianPlayer> E into(E into);
}
